language: python
python:
  - "3.6"
before_install:
  # Install CPU version of PyTorch.
  - if [[ $TRAVIS_PYTHON_VERSION == 3.6 ]]; then pip install torch==1.8.0+cpu torchvision==0.9.0+cpu -f https://download.pytorch.org/whl/torch_stable.html; fi
  # Install remaining dependencies
  - pip install -r requirements.txt
install:
  - python setup.py install
script:
  - pytest
  - pylint --rcfile=.pylintrc joeynmt
