name: "iwslt_deen_bahdanau"

data:
    src: "de"
    trg: "en"
    train: "test/data/iwslt_deen/train"
    dev: "test/data/iwslt_deen/dev"
    test: "test/data/iwslt_deen/test"
    level: "word"
    lowercase: True
    max_sent_length: 50
    src_voc_min_freq: 3
    trg_voc_min_freq: 3
   
testing:
    beam_size: 10
    alpha: 1.0

training:
    random_seed: 42
    optimizer: "adam"
    learning_rate: 0.001
    learning_rate_min: 0.00005
    batch_size: 64
    scheduling: "plateau"
    patience: 0
    decrease_factor: 0.5
    early_stopping_metric: "ppl"
    epochs: 100
    validation_freq: 2359
    logging_freq: 500
    eval_metric: "bleu"
    model_dir: "models/iwslt_deen_bahdanau"
    overwrite: False
    shuffle: True
    use_cuda: True
    max_output_length: 100
    print_valid_sents: [0, 1, 2, 3, 4]

model:
    encoder:
        rnn_type: "lstm"
        embeddings: 
            embedding_dim: 256
            scale: False
        hidden_size: 256
        bidirectional: True
        dropout: 0.0
        num_layers: 1
    decoder:
        rnn_type: "lstm"
        embeddings:
            embedding_dim: 256
            scale: False
        emb_scale: False
        hidden_size: 256
        dropout: 0.2
        hidden_dropout: 0.2
        num_layers: 1
        input_feeding: True
        init_hidden: "last"
        attention: "luong"
