name: "iwslt_envi_luong"

data:
    src: "en"
    trg: "vi"
    train: "test/data/iwslt_envi/train"
    dev: "test/data/iwslt_envi/tst2012"
    test: "test/data/iwslt_envi/tst2013"
    level: "word"
    lowercase: False
    max_sent_length: 50
    src_voc_min_freq: 0
    src_voc_limit: 100000
    trg_voc_min_freq: 0
    trg_voc_limit: 100000
    src_vocab: "test/data/iwslt_envi/vocab.en"
    trg_vocab: "test/data/iwslt_envi/vocab.vi"

testing:
    beam_size: 10
    alpha: 1.0

training:
    #load_model: "iwslt_envi_luong/XXXXX.cpkt"
    random_seed: 42
    optimizer: "sgd"
    learning_rate: 1.0
    learning_rate_min: 0.0625
    weight_decay: 0.0
    clip_grad_norm: 5.0
    batch_size: 128
    scheduling: "plateau"
    patience: 1
    decrease_factor: 0.5
    early_stopping_metric: "eval_metric"
    epochs: 25
    validation_freq: 1000
    logging_freq: 100
    eval_metric: "bleu"
    model_dir: "models/iwslt_envi_luong"
    overwrite: True
    shuffle: True
    use_cuda: True
    max_output_length: 150
    print_valid_sents: [0, 1, 2]

model:
    initializer: "uniform"
    init_weight: 0.1
    embed_initializer: "uniform"
    embed_init_weight: 0.1
    bias_initializer: "uniform"
    bias_init_weight: 0.1
    init_rnn_orthogonal: False
    lstm_forget_gate: 0.
    encoder:
        rnn_type: "lstm"
        embeddings:
            embedding_dim: 512
            scale: False
        hidden_size: 512
        bidirectional: True
        dropout: 0.2
        num_layers: 1
    decoder:
        rnn_type: "lstm"
        embeddings:
            embedding_dim: 512
            scale: False
        emb_scale: False
        hidden_size: 512
        dropout: 0.2
        hidden_dropout: 0.2
        num_layers: 2
        input_feeding: True
        init_hidden: "zero"
        attention: "luong"
