name: "experiment"

data:
    src: "en"
    trg: "vi"
    train: "test/data/iwslt_envi/train"
    dev: "test/data/iwslt_envi/tst2012"
    test: "test/data/iwslt_envi/tst2013"
    level: "word"
    lowercase: False
    max_sent_length: 110
    src_voc_min_freq: 0
    src_voc_limit: 100000
    trg_voc_min_freq: 0
    trg_voc_limit: 100000
    src_vocab: "test/data/iwslt_envi/vocab.en"
    trg_vocab: "test/data/iwslt_envi/vocab.vi"

testing:
    beam_size: 5
    alpha: 1.0

training:
    #load_model: "iwslt_envi_xnmt/XXX.cpkt"
    random_seed: 42
    optimizer: "adam"
    learning_rate: 0.001
    learning_rate_min: 0.00005
    weight_decay: 0.0
    clip_grad_norm: 1.0
    batch_size: 64
    scheduling: "plateau"
    patience: 1
    decrease_factor: 0.5
    early_stopping_metric: "eval_metric"
    epochs: 30
    validation_freq: 1000
    logging_freq: 100
    eval_metric: "bleu"
    model_dir: "models/iwslt_envi_xnmt"
    overwrite: True
    shuffle: True
    use_cuda: True
    max_output_length: 150
    print_valid_sents: [0, 1, 2]

model:
    initializer: "xavier"
    embed_initializer: "normal"
    embed_init_weight: 0.1
    bias_initializer: "zeros"
    init_rnn_orthogonal: False
    lstm_forget_gate: 0.
    encoder:
        rnn_type: "lstm"
        embeddings:
            embedding_dim: 128
            scale: False
        hidden_size: 512
        bidirectional: True
        dropout: 0.3
        num_layers: 1
    decoder:
        rnn_type: "lstm"
        embeddings:
            embedding_dim: 128
            scale: False
        hidden_size: 512
        dropout: 0.3
        hidden_dropout: 0.3
        num_layers: 1
        input_feeding: True
        init_hidden: "zero"
        attention: "bahdanau"
