name: "jparacrawl_enja_sp"
joeynmt_version: "2.0.0"

data:
    train: "jparacrawl"
    dev: "wmt21"
    test: "kftt"
    dataset_type: "huggingface"
    dataset_cfg:
        name: "ja-en"
    sample_train_subset: -1
    sample_dev_subset: 200
    src:
        lang: "en"
        max_length: 512
        lowercase: False
        normalize: True
        level: "bpe"
        voc_limit: 32000
        voc_min_freq: 1
        voc_file: "subwords/jparacrawl_en.vocab"
        tokenizer_type: "sentencepiece"
        tokenizer_cfg:
            model_file: "subwords/jparacrawl_en.model"
            model_type: "unigram"
            character_coverage: 1.0
            nbest_size: 10
            alpha: 0.1
    trg:
        lang: "ja"
        max_length: 512
        lowercase: False
        normalize: True
        level: "bpe"
        voc_limit: 32000
        voc_min_freq: 1
        voc_file: "subwords/jparacrawl_ja.vocab"
        tokenizer_type: "sentencepiece"
        tokenizer_cfg:
            model_file: "subwords/jparacrawl_ja.model"
            model_type: "unigram"
            character_coverage: 0.995
            nbest_size: 10
            alpha: 0.1

testing:
    n_best: 1
    beam_size: 6
    beam_alpha: 1.0
    batch_size: 1024
    batch_type: "token"
    max_output_length: 100
    eval_metrics: ["bleu"]
    return_prob: "none"
    return_attention: False
    generate_unk: False
    no_repeat_ngram_size: 4
    repetition_penalty: -1
    sacrebleu_cfg:
        tokenize: "ja-mecab"

training:
    #load_model: "models/jparacrawl_enja_sp/best.ckpt"
    random_seed: 42
    optimizer: "adam"
    normalization: "tokens"
    adam_betas: [0.9, 0.98]
    scheduling: "warmupinversesquareroot"
    learning_rate_warmup: 4000
    learning_rate: 0.001
    learning_rate_min: 0.00000001
    weight_decay: 0.0
    label_smoothing: 0.1
    clip_grad_norm: 1.0
    loss: "crossentropy"
    batch_size: 5120
    batch_type: "token"
    batch_multiplier: 10
    early_stopping_metric: "ppl"
    epochs: 100
    updates: 36000
    validation_freq: 1000
    logging_freq: 100
    model_dir: "models/jparacrawl_enja"
    overwrite: False
    shuffle: True
    use_cuda: True
    print_valid_sents: [0, 1, 2, 3]
    keep_best_ckpts: 3

model:
    initializer: "xavier_uniform"
    bias_initializer: "zeros"
    init_gain: 1.0
    embed_initializer: "xavier_uniform"
    embed_init_gain: 1.0
    tied_embeddings: False
    tied_softmax: False
    encoder:
        type: "transformer"
        num_layers: 6
        num_heads: 8
        embeddings:
            embedding_dim: 512
            scale: True
            dropout: 0.1
        # typically ff_size = 4 x hidden_size
        hidden_size: 512
        ff_size: 2048
        dropout: 0.1
        layer_norm: "pre"
        activation: "relu"
    decoder:
        type: "transformer"
        num_layers: 6
        num_heads: 8
        embeddings:
            embedding_dim: 512
            scale: True
            dropout: 0.1
        # typically ff_size = 4 x hidden_size
        hidden_size: 512
        ff_size: 2048
        dropout: 0.1
        layer_norm: "pre"
        activation: "relu"
